---
name: Deploy

on:
  push:
    branches:
      - main
      - security
    paths-ignore:
      - "*.md"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  LOCATION: westeurope
  RESOURCE_GROUP: BDSA2022
  CONTAINER_REGISTRY: bdsa2022registry
  SQL_ADMINISTRATORS_GROUP_DISPLAY_NAME: BDSA2022-Admins
  SQL_ADMINISTRATORS_GROUP_MAIL_NICKNAME: bdsa2022-admins

jobs:
  deploy:
    name: Deploy
    environment:
      name: Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create SQL Administrators Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            SQL_ADMINISTRATORS_GROUP_OBJECT_ID=$(az ad group create --display-name "${{ env.SQL_ADMINISTRATORS_GROUP_DISPLAY_NAME }}" --mail-nickname ${{ env.SQL_ADMINISTRATORS_GROUP_MAIL_NICKNAME }} --query id --output tsv)
            echo "SQL_ADMINISTRATORS_GROUP_OBJECT_ID=$SQL_ADMINISTRATORS_GROUP_OBJECT_ID" >> $GITHUB_ENV

      - name: Add Service Principal To SQL Administrators Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            SERVICE_PRINCIPAL_OBJECT_ID=$(az ad sp show --id ${{ secrets.AZURE_CLIENT_ID }} --query id --output tsv)
            IS_MEMBER=(az ad group member check --group MyGroupDisplayName --member-id $SERVICE_PRINCIPAL_OBJECT_ID --query value --output tsv)
            if [$IS_MEMBER=='false']
            then
              az ad group member add --group ${{ env.SQL_ADMINISTRATORS_GROUP_OBJECT_ID }} --member-id $SERVICE_PRINCIPAL_OBJECT_ID
            fi

      - name: Create Resource Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}

      - name: Deploy Resources
        uses: Azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./azuredeploy.bicep
          parameters: ./azuredeploy.parameters.json sqlAdministratorsGroupObjectId=${{ env.SQL_ADMINISTRATORS_GROUP_OBJECT_ID }}

      - name: Login To Azure Container Registry
        uses: azure/CLI@v1
        with:
          inlineScript: |
            CONTAINER_REGISTRY_PASSWORD=$(az acr credential show --name ${{ env.CONTAINER_REGISTRY }} --query passwords[0].value --output tsv)
            az acr login --name ${{ env.CONTAINER_REGISTRY }} --username ${{ env.CONTAINER_REGISTRY }} --password $CONTAINER_REGISTRY_PASSWORD --expose-token

      - name: Publish API To Azure Container Registry
        run: dotnet publish ./MyApp.Api --os linux --arch x64 --configuration Release
